services:
  - type: web
    name: fake-news-detector
    env: python
    plan: free
    region: oregon  # location
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python interface/app.py"
    envVars:
      - key: FLASK_ENV
        value: production
